### ISSUE TITLE
[UI Issue] : Background of the HTML is white

### ISSUE THREAD

**Issue by TartejBrothers** [GriffinBaxter/GriffinBaxter.com#3]
# Issue 
- The background of the HTML is white and while overflowing, it shows white colour instead of the footer and header color.

# Fix
 ```css
html{
      background-color: #021431;
}
```
 This should fix the overflow problem.
